; PlatformIO Project Configuration File
; LightLess - ESP32 Firmware
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Puerto serie detectado en Mac
upload_port = /dev/cu.usbserial-210

; Velocidad de subida y monitor
upload_speed = 115200
monitor_speed = 115200
monitor_port = /dev/cu.usbserial-210

; Dependencias
lib_deps =
    knolleary/PubSubClient@^2.8